### ISSUE TITLE
no ID_map_info in data

### ISSUE THREAD

**Issue by qjing666** [farrecall/SCPR#3]
您好，目前下载的数据中，没有ID_map_info文件夹，导致RL训练时报错，请问tag_reverse_map.json 文件和 merged_tag_map.json 是同一个么？

**Comment by gangyizh** [comment]
Data 已更新。Tencent Weiyun：https://share.weiyun.com/ctZX2rnq

**Comment by qjing666** [comment]
> Data 已更新。Tencent Weiyun：https://share.weiyun.com/ctZX2rnq

感谢！
